"""Nutrition seed data for Phase 5 — Indian + international foods.

IMPORTANT DATA QUALITY NOTES:
  * data_quality="VERIFIED" — values from USDA FoodData Central or
    Indian Food Composition Tables (IFCT 2017, NIN India).
  * data_quality="ESTIMATED" — approximated from similar foods or averages.
    These are clearly labelled. Do NOT treat as medically authoritative.
  * All values are per 100g of the food item.
  * No AI-generated nutritional values are used.
  * Source references are included in data_source field.

Usage::

    from app.db.nutrition_seed import SEED_FOODS, SEED_SERVING_OPTIONS
    # Used by the NutritionService to seed the database on first run,
    # or by a management command.

References:
  - USDA FoodData Central: https://fdc.nal.usda.gov/
  - IFCT 2017: Indian Food Composition Tables, NIN India
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any


@dataclass
class SeedServingOption:
    serving_label: str
    quantity_grams: float
    is_default: bool = False
    sort_order: int = 0


@dataclass
class SeedFood:
    name_en: str
    category: str
    diet_type: str
    calories_per_100g: float
    protein_g: float
    carbs_g: float
    fat_g: float
    fiber_g: float
    sugar_g: float = 0.0
    sodium_mg: float = 0.0
    name_hi: str | None = None
    name_regional: str | None = None
    cuisine: str | None = None
    search_aliases: list[str] = field(default_factory=list)
    iron_mg: float | None = None
    calcium_mg: float | None = None
    folate_mcg: float | None = None
    data_quality: str = "ESTIMATED"
    data_source: str | None = None
    serving_options: list[SeedServingOption] = field(default_factory=list)


IFCT = "IFCT 2017 - National Institute of Nutrition, India"
USDA = "USDA FoodData Central (fdc.nal.usda.gov)"
ESTIMATED = "ESTIMATED"

SEED_FOODS: list[SeedFood] = [
    # -----------------------------------------------------------------------
    # GRAINS — Rotis, Bread, Rice
    # -----------------------------------------------------------------------
    SeedFood(
        name_en="Wheat Roti (Chapati)",
        name_hi="रोटी",
        name_regional="Phulka / Chapati",
        category="GRAINS",
        cuisine="North Indian",
        diet_type="VEGAN",
        calories_per_100g=297.0,
        protein_g=9.7,
        carbs_g=52.9,
        fat_g=3.7,
        fiber_g=3.9,
        sugar_g=0.3,
        sodium_mg=393.0,
        iron_mg=4.0,
        calcium_mg=49.0,
        search_aliases=["roti", "chapati", "phulka", "wheat roti", "atta roti", "chappati"],
        data_quality="VERIFIED",
        data_source=IFCT,
        serving_options=[
            SeedServingOption("1 roti (small)", 40.0, is_default=True, sort_order=1),
            SeedServingOption("1 roti (medium)", 50.0, sort_order=2),
            SeedServingOption("2 roti", 80.0, sort_order=3),
            SeedServingOption("3 roti", 120.0, sort_order=4),
            SeedServingOption("100g", 100.0, sort_order=5),
        ],
    ),
    SeedFood(
        name_en="Paratha (Plain)",
        name_hi="पराठा",
        category="GRAINS",
        cuisine="North Indian",
        diet_type="VEGETARIAN",
        calories_per_100g=326.0,
        protein_g=8.1,
        carbs_g=48.9,
        fat_g=11.5,
        fiber_g=3.5,
        sugar_g=0.3,
        sodium_mg=449.0,
        search_aliases=["paratha", "parata", "plain paratha"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 paratha", 80.0, is_default=True, sort_order=1),
            SeedServingOption("2 paratha", 160.0, sort_order=2),
            SeedServingOption("100g", 100.0, sort_order=3),
        ],
    ),
    SeedFood(
        name_en="Aloo Paratha",
        name_hi="आलू पराठा",
        category="GRAINS",
        cuisine="North Indian",
        diet_type="VEGETARIAN",
        calories_per_100g=234.0,
        protein_g=6.5,
        carbs_g=38.5,
        fat_g=6.5,
        fiber_g=3.2,
        sugar_g=1.0,
        sodium_mg=350.0,
        search_aliases=["aloo paratha", "potato paratha", "stuffed paratha"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 paratha", 120.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Cooked Rice (White)",
        name_hi="चावल",
        category="GRAINS",
        cuisine="Pan-Indian",
        diet_type="VEGAN",
        calories_per_100g=130.0,
        protein_g=2.7,
        carbs_g=28.2,
        fat_g=0.3,
        fiber_g=0.4,
        sugar_g=0.0,
        sodium_mg=1.0,
        iron_mg=0.2,
        search_aliases=["rice", "chawal", "cooked rice", "white rice", "plain rice", "bhaat"],
        data_quality="VERIFIED",
        data_source=USDA,
        serving_options=[
            SeedServingOption("1 small bowl (150g)", 150.0, is_default=True, sort_order=1),
            SeedServingOption("1 cup (186g)", 186.0, sort_order=2),
            SeedServingOption("1 large plate", 300.0, sort_order=3),
            SeedServingOption("100g", 100.0, sort_order=4),
        ],
    ),
    SeedFood(
        name_en="Brown Rice (Cooked)",
        name_hi="ब्राउन राइस",
        category="GRAINS",
        cuisine="Pan-Indian",
        diet_type="VEGAN",
        calories_per_100g=123.0,
        protein_g=2.6,
        carbs_g=25.6,
        fat_g=0.9,
        fiber_g=1.8,
        sugar_g=0.3,
        sodium_mg=4.0,
        iron_mg=0.5,
        search_aliases=["brown rice", "whole grain rice", "unpolished rice"],
        data_quality="VERIFIED",
        data_source=USDA,
        serving_options=[
            SeedServingOption("1 bowl (150g)", 150.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Poha (Cooked)",
        name_hi="पोहा",
        category="GRAINS",
        cuisine="West Indian / Maharashtrian",
        diet_type="VEGAN",
        calories_per_100g=130.0,
        protein_g=2.5,
        carbs_g=26.8,
        fat_g=1.5,
        fiber_g=0.5,
        sugar_g=1.5,
        sodium_mg=200.0,
        search_aliases=["poha", "poha breakfast", "flattened rice", "beaten rice", "chivda", "aval"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 plate (200g)", 200.0, is_default=True, sort_order=1),
            SeedServingOption("1 small bowl (150g)", 150.0, sort_order=2),
            SeedServingOption("100g", 100.0, sort_order=3),
        ],
    ),
    SeedFood(
        name_en="Upma (Cooked)",
        name_hi="उपमा",
        category="GRAINS",
        cuisine="South Indian",
        diet_type="VEGETARIAN",
        calories_per_100g=138.0,
        protein_g=4.2,
        carbs_g=22.5,
        fat_g=3.5,
        fiber_g=1.5,
        sugar_g=1.0,
        sodium_mg=450.0,
        search_aliases=["upma", "rava upma", "semolina upma", "suji upma"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 plate (200g)", 200.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),

    # -----------------------------------------------------------------------
    # PULSES — Dal, Chhole, Rajma
    # -----------------------------------------------------------------------
    SeedFood(
        name_en="Toor Dal (Cooked)",
        name_hi="तूर दाल",
        name_regional="Arhar Dal",
        category="PULSES",
        cuisine="Pan-Indian",
        diet_type="VEGAN",
        calories_per_100g=104.0,
        protein_g=6.8,
        carbs_g=17.3,
        fat_g=0.4,
        fiber_g=4.0,
        sugar_g=1.5,
        sodium_mg=450.0,
        iron_mg=1.6,
        calcium_mg=40.0,
        folate_mcg=55.0,
        search_aliases=["toor dal", "arhar dal", "yellow dal", "pigeon pea dal", "tur dal"],
        data_quality="VERIFIED",
        data_source=IFCT,
        serving_options=[
            SeedServingOption("1 katori/bowl (150g)", 150.0, is_default=True, sort_order=1),
            SeedServingOption("1 cup (200g)", 200.0, sort_order=2),
            SeedServingOption("100g", 100.0, sort_order=3),
        ],
    ),
    SeedFood(
        name_en="Moong Dal (Cooked)",
        name_hi="मूंग दाल",
        category="PULSES",
        cuisine="Pan-Indian",
        diet_type="VEGAN",
        calories_per_100g=105.0,
        protein_g=7.0,
        carbs_g=17.5,
        fat_g=0.4,
        fiber_g=4.5,
        sugar_g=1.0,
        sodium_mg=300.0,
        iron_mg=1.8,
        calcium_mg=27.0,
        folate_mcg=80.0,
        search_aliases=["moong dal", "mung dal", "green gram dal", "yellow moong"],
        data_quality="VERIFIED",
        data_source=IFCT,
        serving_options=[
            SeedServingOption("1 katori/bowl (150g)", 150.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Masoor Dal (Cooked)",
        name_hi="मसूर दाल",
        category="PULSES",
        cuisine="North Indian",
        diet_type="VEGAN",
        calories_per_100g=115.0,
        protein_g=8.0,
        carbs_g=18.0,
        fat_g=0.5,
        fiber_g=4.0,
        sugar_g=1.5,
        sodium_mg=400.0,
        iron_mg=3.3,
        folate_mcg=120.0,
        search_aliases=["masoor dal", "red lentil dal", "red lentils", "lentil soup"],
        data_quality="VERIFIED",
        data_source=IFCT,
        serving_options=[
            SeedServingOption("1 katori/bowl (150g)", 150.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Chana Dal (Cooked)",
        name_hi="चना दाल",
        category="PULSES",
        cuisine="Pan-Indian",
        diet_type="VEGAN",
        calories_per_100g=164.0,
        protein_g=8.7,
        carbs_g=27.5,
        fat_g=2.7,
        fiber_g=7.6,
        iron_mg=1.5,
        search_aliases=["chana dal", "split chickpeas", "bengal gram dal"],
        data_quality="VERIFIED",
        data_source=IFCT,
        serving_options=[
            SeedServingOption("1 katori/bowl (150g)", 150.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Rajma Curry (Cooked)",
        name_hi="राजमा",
        category="PULSES",
        cuisine="North Indian / Punjabi",
        diet_type="VEGAN",
        calories_per_100g=117.0,
        protein_g=7.5,
        carbs_g=17.0,
        fat_g=2.0,
        fiber_g=5.5,
        iron_mg=2.0,
        search_aliases=["rajma", "kidney beans curry", "rajma chawal", "red kidney beans"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 katori/bowl (150g)", 150.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Chole (Chickpea Curry)",
        name_hi="छोले",
        category="PULSES",
        cuisine="North Indian / Punjabi",
        diet_type="VEGAN",
        calories_per_100g=130.0,
        protein_g=8.0,
        carbs_g=18.5,
        fat_g=3.0,
        fiber_g=6.0,
        iron_mg=2.5,
        folate_mcg=40.0,
        search_aliases=["chole", "chana masala", "chickpea curry", "kabuli chana", "chhole"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 katori/bowl (150g)", 150.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Khichdi (Rice & Moong Dal)",
        name_hi="खिचड़ी",
        category="GRAINS",
        cuisine="Pan-Indian",
        diet_type="VEGAN",
        calories_per_100g=110.0,
        protein_g=4.5,
        carbs_g=20.5,
        fat_g=1.5,
        fiber_g=2.0,
        search_aliases=["khichdi", "khichri", "dal khichdi", "rice dal", "pongal"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 bowl (200g)", 200.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),

    # -----------------------------------------------------------------------
    # DAIRY
    # -----------------------------------------------------------------------
    SeedFood(
        name_en="Whole Milk (Cow)",
        name_hi="दूध",
        category="DAIRY",
        cuisine=None,
        diet_type="VEGETARIAN",
        calories_per_100g=61.0,
        protein_g=3.2,
        carbs_g=4.7,
        fat_g=3.3,
        fiber_g=0.0,
        sugar_g=4.7,
        sodium_mg=44.0,
        calcium_mg=113.0,
        iron_mg=0.1,
        search_aliases=["milk", "doodh", "cow milk", "full fat milk", "whole milk"],
        data_quality="VERIFIED",
        data_source=IFCT,
        serving_options=[
            SeedServingOption("1 glass (200ml)", 200.0, is_default=True, sort_order=1),
            SeedServingOption("1 cup (240ml)", 240.0, sort_order=2),
            SeedServingOption("100ml", 100.0, sort_order=3),
        ],
    ),
    SeedFood(
        name_en="Curd / Yogurt",
        name_hi="दही",
        category="DAIRY",
        cuisine="Pan-Indian",
        diet_type="VEGETARIAN",
        calories_per_100g=63.0,
        protein_g=3.5,
        carbs_g=4.9,
        fat_g=3.4,
        fiber_g=0.0,
        sugar_g=4.9,
        sodium_mg=46.0,
        calcium_mg=120.0,
        search_aliases=["dahi", "curd", "yogurt", "yoghurt", "plain yogurt"],
        data_quality="VERIFIED",
        data_source=IFCT,
        serving_options=[
            SeedServingOption("1 katori (100g)", 100.0, is_default=True, sort_order=1),
            SeedServingOption("1 cup (200g)", 200.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Paneer (Cottage Cheese)",
        name_hi="पनीर",
        category="DAIRY",
        cuisine="North Indian",
        diet_type="VEGETARIAN",
        calories_per_100g=265.0,
        protein_g=18.3,
        carbs_g=1.2,
        fat_g=20.8,
        fiber_g=0.0,
        sodium_mg=28.0,
        calcium_mg=480.0,
        search_aliases=["paneer", "cottage cheese", "fresh cheese", "Indian cheese"],
        data_quality="VERIFIED",
        data_source=IFCT,
        serving_options=[
            SeedServingOption("50g (small serving)", 50.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
            SeedServingOption("150g", 150.0, sort_order=3),
        ],
    ),
    SeedFood(
        name_en="Ghee (Clarified Butter)",
        name_hi="घी",
        category="DAIRY",
        cuisine="Pan-Indian",
        diet_type="VEGETARIAN",
        calories_per_100g=900.0,
        protein_g=0.0,
        carbs_g=0.0,
        fat_g=99.5,
        fiber_g=0.0,
        search_aliases=["ghee", "clarified butter", "desi ghee"],
        data_quality="VERIFIED",
        data_source=IFCT,
        serving_options=[
            SeedServingOption("1 tsp (5g)", 5.0, is_default=True, sort_order=1),
            SeedServingOption("1 tbsp (15g)", 15.0, sort_order=2),
        ],
    ),

    # -----------------------------------------------------------------------
    # SOUTH INDIAN STAPLES
    # -----------------------------------------------------------------------
    SeedFood(
        name_en="Idli (Steamed)",
        name_hi="इडली",
        category="GRAINS",
        cuisine="South Indian",
        diet_type="VEGAN",
        calories_per_100g=140.0,
        protein_g=3.4,
        carbs_g=28.3,
        fat_g=0.5,
        fiber_g=0.6,
        sodium_mg=270.0,
        iron_mg=1.2,
        search_aliases=["idli", "idly", "steamed rice cake", "south indian idli"],
        data_quality="VERIFIED",
        data_source=IFCT,
        serving_options=[
            SeedServingOption("1 idli (50g)", 50.0, sort_order=1),
            SeedServingOption("2 idli (100g)", 100.0, is_default=True, sort_order=2),
            SeedServingOption("3 idli (150g)", 150.0, sort_order=3),
            SeedServingOption("4 idli (200g)", 200.0, sort_order=4),
        ],
    ),
    SeedFood(
        name_en="Masala Dosa",
        name_hi="डोसा",
        category="GRAINS",
        cuisine="South Indian",
        diet_type="VEGAN",
        calories_per_100g=168.0,
        protein_g=3.5,
        carbs_g=25.0,
        fat_g=6.0,
        fiber_g=1.5,
        sodium_mg=350.0,
        search_aliases=["masala dosa", "dosa", "dosai", "south indian dosa", "crispy dosa", "paper dosa"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 dosa (150g)", 150.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Sambar",
        name_hi="सांभर",
        category="PULSES",
        cuisine="South Indian",
        diet_type="VEGAN",
        calories_per_100g=38.0,
        protein_g=2.4,
        carbs_g=5.5,
        fat_g=0.8,
        fiber_g=2.0,
        iron_mg=1.0,
        search_aliases=["sambar", "sambhar", "south indian lentil soup", "tamarind dal"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 bowl (200ml)", 200.0, is_default=True, sort_order=1),
            SeedServingOption("100ml", 100.0, sort_order=2),
        ],
    ),

    # -----------------------------------------------------------------------
    # VEGETABLES
    # -----------------------------------------------------------------------
    SeedFood(
        name_en="Palak Paneer",
        name_hi="पालक पनीर",
        category="VEGETABLES",
        cuisine="North Indian",
        diet_type="VEGETARIAN",
        calories_per_100g=140.0,
        protein_g=8.0,
        carbs_g=7.0,
        fat_g=9.0,
        fiber_g=2.5,
        iron_mg=3.0,
        calcium_mg=220.0,
        folate_mcg=80.0,
        search_aliases=["palak paneer", "spinach paneer", "saag paneer"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 katori/bowl (150g)", 150.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Mixed Vegetable Sabzi",
        name_hi="मिक्स सब्जी",
        category="VEGETABLES",
        cuisine="North Indian",
        diet_type="VEGAN",
        calories_per_100g=80.0,
        protein_g=2.5,
        carbs_g=12.0,
        fat_g=2.5,
        fiber_g=3.0,
        search_aliases=["sabzi", "sabji", "mixed vegetables", "veg curry", "subzi"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 katori/bowl (150g)", 150.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Aloo Gobhi",
        name_hi="आलू गोभी",
        category="VEGETABLES",
        cuisine="North Indian",
        diet_type="VEGAN",
        calories_per_100g=95.0,
        protein_g=2.5,
        carbs_g=15.0,
        fat_g=3.0,
        fiber_g=2.5,
        search_aliases=["aloo gobhi", "potato cauliflower", "gobhi sabzi"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 katori/bowl (150g)", 150.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Baingan Bharta",
        name_hi="बैंगन भर्ता",
        category="VEGETABLES",
        cuisine="North Indian",
        diet_type="VEGAN",
        calories_per_100g=70.0,
        protein_g=2.0,
        carbs_g=8.5,
        fat_g=3.0,
        fiber_g=3.5,
        search_aliases=["baingan bharta", "eggplant curry", "brinjal curry", "baingan"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 katori/bowl (150g)", 150.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Spinach (Raw)",
        name_hi="पालक",
        category="VEGETABLES",
        cuisine=None,
        diet_type="VEGAN",
        calories_per_100g=23.0,
        protein_g=2.9,
        carbs_g=3.6,
        fat_g=0.4,
        fiber_g=2.2,
        iron_mg=2.7,
        calcium_mg=99.0,
        folate_mcg=194.0,
        search_aliases=["spinach", "palak", "saag", "leafy greens"],
        data_quality="VERIFIED",
        data_source=USDA,
        serving_options=[
            SeedServingOption("1 cup raw (30g)", 30.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),

    # -----------------------------------------------------------------------
    # FRUITS
    # -----------------------------------------------------------------------
    SeedFood(
        name_en="Banana",
        name_hi="केला",
        category="FRUITS",
        cuisine=None,
        diet_type="VEGAN",
        calories_per_100g=89.0,
        protein_g=1.1,
        carbs_g=22.8,
        fat_g=0.3,
        fiber_g=2.6,
        sugar_g=12.2,
        sodium_mg=1.0,
        iron_mg=0.3,
        search_aliases=["banana", "kela", "plantain"],
        data_quality="VERIFIED",
        data_source=USDA,
        serving_options=[
            SeedServingOption("1 small banana (80g)", 80.0, sort_order=1),
            SeedServingOption("1 medium banana (100g)", 100.0, is_default=True, sort_order=2),
            SeedServingOption("1 large banana (130g)", 130.0, sort_order=3),
        ],
    ),
    SeedFood(
        name_en="Apple",
        name_hi="सेब",
        category="FRUITS",
        cuisine=None,
        diet_type="VEGAN",
        calories_per_100g=52.0,
        protein_g=0.3,
        carbs_g=13.8,
        fat_g=0.2,
        fiber_g=2.4,
        sugar_g=10.4,
        sodium_mg=1.0,
        search_aliases=["apple", "seb"],
        data_quality="VERIFIED",
        data_source=USDA,
        serving_options=[
            SeedServingOption("1 small apple (150g)", 150.0, sort_order=1),
            SeedServingOption("1 medium apple (182g)", 182.0, is_default=True, sort_order=2),
            SeedServingOption("100g", 100.0, sort_order=3),
        ],
    ),
    SeedFood(
        name_en="Mango",
        name_hi="आम",
        category="FRUITS",
        cuisine=None,
        diet_type="VEGAN",
        calories_per_100g=60.0,
        protein_g=0.8,
        carbs_g=15.0,
        fat_g=0.4,
        fiber_g=1.6,
        sugar_g=13.7,
        iron_mg=0.2,
        folate_mcg=43.0,
        search_aliases=["mango", "aam", "alphonso", "kesar mango", "raw mango", "keri"],
        data_quality="VERIFIED",
        data_source=IFCT,
        serving_options=[
            SeedServingOption("1/2 mango (150g)", 150.0, is_default=True, sort_order=1),
            SeedServingOption("1 cup sliced (165g)", 165.0, sort_order=2),
            SeedServingOption("100g", 100.0, sort_order=3),
        ],
    ),
    SeedFood(
        name_en="Guava",
        name_hi="अमरूद",
        category="FRUITS",
        cuisine=None,
        diet_type="VEGAN",
        calories_per_100g=68.0,
        protein_g=2.6,
        carbs_g=14.3,
        fat_g=1.0,
        fiber_g=5.4,
        sugar_g=8.9,
        iron_mg=0.3,
        folate_mcg=49.0,
        search_aliases=["guava", "amrood", "peru"],
        data_quality="VERIFIED",
        data_source=USDA,
        serving_options=[
            SeedServingOption("1 medium guava (100g)", 100.0, is_default=True, sort_order=1),
        ],
    ),
    SeedFood(
        name_en="Papaya",
        name_hi="पपीता",
        category="FRUITS",
        cuisine=None,
        diet_type="VEGAN",
        calories_per_100g=43.0,
        protein_g=0.5,
        carbs_g=10.8,
        fat_g=0.3,
        fiber_g=1.7,
        sugar_g=7.8,
        iron_mg=0.3,
        folate_mcg=37.0,
        search_aliases=["papaya", "papita", "paw paw"],
        data_quality="VERIFIED",
        data_source=USDA,
        serving_options=[
            SeedServingOption("1 cup cubed (145g)", 145.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),

    # -----------------------------------------------------------------------
    # SNACKS
    # -----------------------------------------------------------------------
    SeedFood(
        name_en="Samosa (Fried)",
        name_hi="समोसा",
        category="SNACKS",
        cuisine="North Indian",
        diet_type="VEGETARIAN",
        calories_per_100g=262.0,
        protein_g=5.1,
        carbs_g=30.0,
        fat_g=14.0,
        fiber_g=2.5,
        sodium_mg=380.0,
        search_aliases=["samosa", "samoosa", "fried samosa", "aloo samosa"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 samosa (60g)", 60.0, is_default=True, sort_order=1),
            SeedServingOption("2 samosa (120g)", 120.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Peanut Chikki",
        name_hi="मूंगफली चिक्की",
        category="SNACKS",
        cuisine="Pan-Indian",
        diet_type="VEGAN",
        calories_per_100g=440.0,
        protein_g=13.0,
        carbs_g=55.0,
        fat_g=20.0,
        fiber_g=3.0,
        sugar_g=42.0,
        search_aliases=["chikki", "peanut chikki", "peanut brittle", "moongfali chikki", "groundnut chikki", "peanut"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 piece (30g)", 30.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Roasted Peanuts",
        name_hi="मूंगफली",
        category="NUTS",
        cuisine=None,
        diet_type="VEGAN",
        calories_per_100g=585.0,
        protein_g=25.8,
        carbs_g=16.1,
        fat_g=49.7,
        fiber_g=8.5,
        sodium_mg=6.0,
        iron_mg=2.3,
        search_aliases=["peanuts", "groundnuts", "moongfali", "roasted peanuts", "salted peanuts"],
        data_quality="VERIFIED",
        data_source=USDA,
        serving_options=[
            SeedServingOption("1 small handful (25g)", 25.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),

    # -----------------------------------------------------------------------
    # BEVERAGES
    # -----------------------------------------------------------------------
    SeedFood(
        name_en="Masala Chai (with milk)",
        name_hi="मसाला चाय",
        category="BEVERAGES",
        cuisine="Pan-Indian",
        diet_type="VEGETARIAN",
        calories_per_100g=37.0,
        protein_g=1.5,
        carbs_g=5.0,
        fat_g=1.3,
        fiber_g=0.0,
        sugar_g=4.5,
        sodium_mg=30.0,
        search_aliases=["chai", "tea", "masala chai", "Indian tea", "cutting chai", "milk tea"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 cup (150ml)", 150.0, is_default=True, sort_order=1),
            SeedServingOption("1 large mug (200ml)", 200.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Lassi (Sweet)",
        name_hi="लस्सी",
        category="BEVERAGES",
        cuisine="North Indian / Punjabi",
        diet_type="VEGETARIAN",
        calories_per_100g=70.0,
        protein_g=3.5,
        carbs_g=10.0,
        fat_g=1.5,
        fiber_g=0.0,
        sugar_g=9.0,
        sodium_mg=50.0,
        calcium_mg=120.0,
        search_aliases=["lassi", "sweet lassi", "yogurt drink", "dahi drink"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 glass (200ml)", 200.0, is_default=True, sort_order=1),
            SeedServingOption("100ml", 100.0, sort_order=2),
        ],
    ),

    # -----------------------------------------------------------------------
    # NON-VEGETARIAN
    # -----------------------------------------------------------------------
    SeedFood(
        name_en="Chicken Curry",
        name_hi="मुर्ग़ की करी",
        category="MEAT",
        cuisine="Pan-Indian",
        diet_type="NON_VEGETARIAN",
        calories_per_100g=165.0,
        protein_g=21.5,
        carbs_g=4.5,
        fat_g=7.0,
        fiber_g=0.5,
        sodium_mg=560.0,
        iron_mg=1.2,
        search_aliases=["chicken curry", "murgi", "murgh curry", "chicken masala", "chicken gravy"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 katori/bowl (150g)", 150.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Egg (Boiled)",
        name_hi="उबला अंडा",
        category="EGGS",
        cuisine=None,
        diet_type="EGGETARIAN",
        calories_per_100g=155.0,
        protein_g=12.6,
        carbs_g=1.1,
        fat_g=10.6,
        fiber_g=0.0,
        sodium_mg=124.0,
        iron_mg=1.2,
        calcium_mg=56.0,
        folate_mcg=44.0,
        search_aliases=["egg", "anda", "boiled egg", "hard boiled egg", "anda boiled", "egg white"],
        data_quality="VERIFIED",
        data_source=USDA,
        serving_options=[
            SeedServingOption("1 large egg (50g)", 50.0, is_default=True, sort_order=1),
            SeedServingOption("2 eggs (100g)", 100.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Fish Curry",
        name_hi="मछली करी",
        category="SEAFOOD",
        cuisine="Pan-Indian / Bengali / Kerala",
        diet_type="NON_VEGETARIAN",
        calories_per_100g=130.0,
        protein_g=18.0,
        carbs_g=3.5,
        fat_g=5.0,
        fiber_g=0.5,
        search_aliases=["fish curry", "machli curry", "fish masala", "meen curry", "bengali fish"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 katori/bowl (150g)", 150.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),

    # -----------------------------------------------------------------------
    # BIRYANI
    # -----------------------------------------------------------------------
    SeedFood(
        name_en="Vegetable Biryani",
        name_hi="वेज बिरयानी",
        category="PREPARED_MEALS",
        cuisine="Hyderabadi / Pan-Indian",
        diet_type="VEGETARIAN",
        calories_per_100g=150.0,
        protein_g=3.5,
        carbs_g=27.0,
        fat_g=3.5,
        fiber_g=2.0,
        sodium_mg=450.0,
        search_aliases=["veg biryani", "vegetable biryani", "biryani", "pulao", "veg pulao"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 plate (250g)", 250.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Chicken Biryani",
        name_hi="चिकन बिरयानी",
        category="PREPARED_MEALS",
        cuisine="Hyderabadi / Mughlai",
        diet_type="NON_VEGETARIAN",
        calories_per_100g=195.0,
        protein_g=11.0,
        carbs_g=24.0,
        fat_g=6.0,
        fiber_g=1.0,
        sodium_mg=600.0,
        search_aliases=["chicken biryani", "biryani", "hyderabadi biryani", "dum biryani"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 plate (300g)", 300.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),

    # -----------------------------------------------------------------------
    # NUTS & SEEDS
    # -----------------------------------------------------------------------
    SeedFood(
        name_en="Almonds",
        name_hi="बादाम",
        category="NUTS",
        cuisine=None,
        diet_type="VEGAN",
        calories_per_100g=579.0,
        protein_g=21.2,
        carbs_g=21.6,
        fat_g=49.9,
        fiber_g=12.5,
        calcium_mg=264.0,
        iron_mg=3.7,
        search_aliases=["almonds", "badam", "almond"],
        data_quality="VERIFIED",
        data_source=USDA,
        serving_options=[
            SeedServingOption("10 almonds (~12g)", 12.0, is_default=True, sort_order=1),
            SeedServingOption("1 handful (25g)", 25.0, sort_order=2),
            SeedServingOption("100g", 100.0, sort_order=3),
        ],
    ),
    SeedFood(
        name_en="Sesame Seeds",
        name_hi="तिल",
        category="SEEDS",
        cuisine=None,
        diet_type="VEGAN",
        calories_per_100g=573.0,
        protein_g=17.7,
        carbs_g=23.5,
        fat_g=49.7,
        fiber_g=11.8,
        iron_mg=14.6,
        calcium_mg=975.0,
        search_aliases=["sesame", "til", "sesame seeds", "til seeds"],
        data_quality="VERIFIED",
        data_source=USDA,
        serving_options=[
            SeedServingOption("1 tsp (3g)", 3.0, is_default=True, sort_order=1),
            SeedServingOption("1 tbsp (9g)", 9.0, sort_order=2),
        ],
    ),

    # -----------------------------------------------------------------------
    # SWEETS
    # -----------------------------------------------------------------------
    SeedFood(
        name_en="Gulab Jamun",
        name_hi="गुलाब जामुन",
        category="SWEETS",
        cuisine="Pan-Indian",
        diet_type="VEGETARIAN",
        calories_per_100g=369.0,
        protein_g=6.5,
        carbs_g=63.0,
        fat_g=11.0,
        fiber_g=0.5,
        sugar_g=55.0,
        search_aliases=["gulab jamun", "jamun", "gulab jaman", "mithai", "Indian sweets"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 piece (40g)", 40.0, is_default=True, sort_order=1),
            SeedServingOption("2 pieces (80g)", 80.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Kheer (Rice Pudding)",
        name_hi="खीर",
        category="SWEETS",
        cuisine="Pan-Indian",
        diet_type="VEGETARIAN",
        calories_per_100g=128.0,
        protein_g=4.0,
        carbs_g=22.0,
        fat_g=3.0,
        fiber_g=0.2,
        sugar_g=14.0,
        calcium_mg=130.0,
        search_aliases=["kheer", "rice pudding", "payasam", "payesh"],
        data_quality="ESTIMATED",
        data_source=ESTIMATED,
        serving_options=[
            SeedServingOption("1 katori (150g)", 150.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),

    # -----------------------------------------------------------------------
    # INTERNATIONAL / GLOBALLY COMMON
    # -----------------------------------------------------------------------
    SeedFood(
        name_en="Oats (Cooked)",
        name_hi="ओट्स",
        category="GRAINS",
        cuisine=None,
        diet_type="VEGAN",
        calories_per_100g=68.0,
        protein_g=2.5,
        carbs_g=12.0,
        fat_g=1.4,
        fiber_g=1.7,
        iron_mg=0.8,
        calcium_mg=10.0,
        search_aliases=["oats", "oatmeal", "porridge", "rolled oats", "dalia"],
        data_quality="VERIFIED",
        data_source=USDA,
        serving_options=[
            SeedServingOption("1 bowl (250g cooked)", 250.0, is_default=True, sort_order=1),
            SeedServingOption("100g", 100.0, sort_order=2),
        ],
    ),
    SeedFood(
        name_en="Whole Wheat Bread",
        name_hi="गेहूं की ब्रेड",
        category="GRAINS",
        cuisine=None,
        diet_type="VEGAN",
        calories_per_100g=247.0,
        protein_g=13.0,
        carbs_g=41.3,
        fat_g=4.2,
        fiber_g=6.9,
        sodium_mg=450.0,
        iron_mg=3.4,
        search_aliases=["bread", "whole wheat bread", "brown bread", "atta bread", "multigrain bread"],
        data_quality="VERIFIED",
        data_source=USDA,
        serving_options=[
            SeedServingOption("1 slice (30g)", 30.0, is_default=True, sort_order=1),
            SeedServingOption("2 slices (60g)", 60.0, sort_order=2),
        ],
    ),
]
