"""
Pydantic schemas for the Sakhi AI content ingestion pipeline.
These define the exact JSON structures that the LLM must return.
"""
from typing import List, Optional
from pydantic import BaseModel, Field


# ──────────────────────────────────────────────
# Sub-models
# ──────────────────────────────────────────────

class Source(BaseModel):
    """A cited source for an article."""
    name: str = Field(..., description="Name of the source, e.g. 'MedlinePlus'")
    url: Optional[str] = Field(None, description="URL of the source")


class ArticleSection(BaseModel):
    """A content section within an article."""
    heading: str = Field(..., description="Section heading")
    content: str = Field(..., description="Section content in 2-5 paragraphs")


class FAQ(BaseModel):
    """A frequently asked question and answer."""
    question: str
    answer: str


class MythFact(BaseModel):
    """A myth vs fact pair."""
    myth: str = Field(..., description="A common misconception")
    fact: str = Field(..., description="The accurate, evidence-based fact")


# ──────────────────────────────────────────────
# Main article schema (English generation)
# ──────────────────────────────────────────────

class GeneratedArticle(BaseModel):
    """Full structured article as generated by the LLM."""
    title: str = Field(..., description="Article title")
    short_description: str = Field(..., description="1-2 sentence summary for card/preview, max 200 chars")
    tldr: str = Field(..., description="3-5 sentence plain-language summary of the whole article")
    introduction: str = Field(..., description="1-2 paragraph introduction to the topic")
    sections: List[ArticleSection] = Field(..., description="3-6 content sections with headings and body text", min_length=3)
    myths_vs_facts: List[MythFact] = Field(..., description="2-4 common myths with correct facts", min_length=2)
    faqs: List[FAQ] = Field(..., description="3-5 frequently asked questions and clear answers", min_length=3)
    key_takeaways: List[str] = Field(..., description="4-6 bullet-point key takeaways from the article", min_length=4)
    medical_disclaimer: str = Field(
        default="This article is for educational purposes only and is not a substitute for professional medical advice. Always consult a qualified healthcare provider for any medical concerns.",
        description="Standard medical disclaimer"
    )
    sources: List[Source] = Field(..., description="List of authoritative sources cited", min_length=1)
    keywords: List[str] = Field(..., description="5-10 SEO keywords relevant to the article", min_length=5)


# ──────────────────────────────────────────────
# Translation schema (Hindi / Marathi)
# ──────────────────────────────────────────────

class GeneratedTranslation(BaseModel):
    """Translated version of an article — mirrors GeneratedArticle but all fields are translated."""
    title: str
    short_description: str
    tldr: str
    introduction: str
    sections: List[ArticleSection]
    myths_vs_facts: List[MythFact]
    faqs: List[FAQ]
    key_takeaways: List[str]
    medical_disclaimer: str
    keywords: List[str]


# ──────────────────────────────────────────────
# Validation schemas
# ──────────────────────────────────────────────

class FactValidationResult(BaseModel):
    """Result of fact-checking an article."""
    is_valid: bool = Field(..., description="True if the article is factually sound")
    dangerous_claims_found: bool = Field(..., description="True if any dangerous medical advice is present")
    unsupported_claims: List[str] = Field(default_factory=list, description="List of claims not supported by the provided research")
    fabricated_citations: List[str] = Field(default_factory=list, description="Any citations or statistics invented by the LLM")
    reason: str = Field(..., description="Brief explanation of the validation result")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Validator's confidence in its assessment, 0-1")


class TranslationValidationResult(BaseModel):
    """Result of validating a translation against the English original."""
    is_valid: bool = Field(..., description="True if translation is accurate and complete")
    missing_warnings: bool = Field(..., description="True if any safety warnings were omitted")
    changed_medical_meaning: bool = Field(..., description="True if any medical meanings were altered")
    reason: str = Field(..., description="Brief explanation of the validation result")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Validator's confidence, 0-1")

