"""Add wellness plans and update cycles

Revision ID: 053a36d64ca5
Revises: a7056c1e80f7
Create Date: 2026-08-27 16:35:14.403525
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053a36d64ca5'
down_revision: Union[str, None] = 'a7056c1e80f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
