"""Add wellness plans and update cycles

Revision ID: a7056c1e80f7
Revises: 007
Create Date: 2026-08-27 16:19:59.720533
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7056c1e80f7'
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('ai_observability_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('GEMINI', 'OPENAI', 'GROQ', 'LOCAL', name='aimodelprovider'), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_observability_logs_request_id'), 'ai_observability_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_ai_observability_logs_user_id'), 'ai_observability_logs', ['user_id'], unique=False)
    op.create_table('health_provider_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE_HEALTH_CONNECT', 'APPLE_HEALTH', 'SAMSUNG_HEALTH', 'WEARABLE', name='providertype'), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'ERROR', 'EXPIRED', name='connectionstatus'), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_provider_connections_user_id'), 'health_provider_connections', ['user_id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('trust_level', sa.Enum('PRIMARY_MEDICAL_GUIDELINE', 'GOVERNMENT_HEALTH', 'MAJOR_MEDICAL_ORGANIZATION', 'PEER_REVIEWED_RESEARCH', 'REFERENCE_MEDICAL_SOURCE', name='trustlevel'), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wellness_goals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('goal_type', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wellness_goals_user_id'), 'wellness_goals', ['user_id'], unique=False)
    op.create_table('external_sync_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('records_imported', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('sync_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['health_provider_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('domain_topic', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('freshness', sa.Enum('CURRENT', 'AGING', 'OUTDATED', 'SUPERSEDED', name='freshnessstatus'), nullable=False),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wellness_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', name='planfrequency'), nullable=False),
    sa.Column('status', sa.Enum('SUGGESTED', 'ACCEPTED', 'COMPLETED', 'SKIPPED', 'DISMISSED', name='planstatus'), nullable=False),
    sa.Column('reasoning', sa.String(), nullable=False),
    sa.Column('source_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['wellness_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wellness_plans_user_id'), 'wellness_plans', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_lessons_category'), table_name='lessons')
    op.drop_index(op.f('idx_lessons_language'), table_name='lessons')
    op.drop_index(op.f('idx_lessons_published'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('idx_analytics_created_at'), table_name='analytics_events')
    op.drop_index(op.f('idx_analytics_event_type'), table_name='analytics_events')
    op.drop_index(op.f('idx_analytics_user_id'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('idx_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('idx_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('lesson_search_index')
    op.drop_index(op.f('idx_lesson_progress_lesson_id'), table_name='lesson_progress')
    op.drop_index(op.f('idx_lesson_progress_status'), table_name='lesson_progress')
    op.drop_index(op.f('idx_lesson_progress_user_id'), table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('idx_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('idx_feedback_category'), table_name='feedback')
    op.drop_index(op.f('idx_feedback_created_at'), table_name='feedback')
    op.drop_index(op.f('idx_feedback_status'), table_name='feedback')
    op.drop_index(op.f('idx_feedback_user_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('idx_media_uploader_id'), table_name='media_files')
    op.drop_table('media_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_files',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('uploader_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('size_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('storage_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('media_files_uploader_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('media_files_pkey')),
    sa.UniqueConstraint('storage_key', name=op.f('media_files_storage_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_media_uploader_id'), 'media_files', ['uploader_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'open'::text"), autoincrement=False, nullable=False),
    sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resolved_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('feedback_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_pkey'))
    )
    op.create_index(op.f('idx_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_index(op.f('idx_feedback_status'), 'feedback', ['status'], unique=False)
    op.create_index(op.f('idx_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('idx_feedback_category'), 'feedback', ['category'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('conversation_messages_conversation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_messages_pkey'))
    )
    op.create_index(op.f('idx_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('preferred_language', sa.TEXT(), server_default=sa.text("'english'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deleted_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('progress_percent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('completed_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('lesson_progress_lesson_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('lesson_progress_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lesson_progress_pkey')),
    sa.UniqueConstraint('user_id', 'lesson_id', name=op.f('lesson_progress_user_id_lesson_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_lesson_progress_user_id'), 'lesson_progress', ['user_id'], unique=False)
    op.create_index(op.f('idx_lesson_progress_status'), 'lesson_progress', ['status'], unique=False)
    op.create_index(op.f('idx_lesson_progress_lesson_id'), 'lesson_progress', ['lesson_id'], unique=False)
    op.create_table('lesson_search_index',
    sa.Column('lesson_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('search_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('lesson_search_index_lesson_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', name=op.f('lesson_search_index_pkey'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('notification_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata_json', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('read_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('idx_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('idx_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('preferred_language', sa.TEXT(), server_default=sa.text("'english'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('conversations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversations_pkey'))
    )
    op.create_index(op.f('idx_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata_json', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('analytics_events_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_events_pkey'))
    )
    op.create_index(op.f('idx_analytics_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_index(op.f('idx_analytics_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('idx_analytics_created_at'), 'analytics_events', ['created_at'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('audience', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tags_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sections_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('translations_json', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=False),
    sa.Column('published', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('lessons_pkey')),
    sa.UniqueConstraint('slug', name=op.f('lessons_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_lessons_published'), 'lessons', ['published'], unique=False)
    op.create_index(op.f('idx_lessons_language'), 'lessons', ['language'], unique=False)
    op.create_index(op.f('idx_lessons_category'), 'lessons', ['category'], unique=False)
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_wellness_plans_user_id'), table_name='wellness_plans')
    op.drop_table('wellness_plans')
    op.drop_table('knowledge_documents')
    op.drop_table('external_sync_logs')
    op.drop_index(op.f('ix_wellness_goals_user_id'), table_name='wellness_goals')
    op.drop_table('wellness_goals')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_health_provider_connections_user_id'), table_name='health_provider_connections')
    op.drop_table('health_provider_connections')
    op.drop_index(op.f('ix_ai_observability_logs_user_id'), table_name='ai_observability_logs')
    op.drop_index(op.f('ix_ai_observability_logs_request_id'), table_name='ai_observability_logs')
    op.drop_table('ai_observability_logs')
    # ### end Alembic commands ###
