"""Add wellness plans and update cycles

Revision ID: a7056c1e80f7
Revises: 007
Create Date: 2026-08-27 16:19:59.720533
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7056c1e80f7'
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('ai_observability_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('GEMINI', 'OPENAI', 'GROQ', 'LOCAL', name='aimodelprovider'), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_observability_logs_request_id'), 'ai_observability_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_ai_observability_logs_user_id'), 'ai_observability_logs', ['user_id'], unique=False)
    op.create_table('health_provider_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE_HEALTH_CONNECT', 'APPLE_HEALTH', 'SAMSUNG_HEALTH', 'WEARABLE', name='providertype'), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'ERROR', 'EXPIRED', name='connectionstatus'), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_provider_connections_user_id'), 'health_provider_connections', ['user_id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('trust_level', sa.Enum('PRIMARY_MEDICAL_GUIDELINE', 'GOVERNMENT_HEALTH', 'MAJOR_MEDICAL_ORGANIZATION', 'PEER_REVIEWED_RESEARCH', 'REFERENCE_MEDICAL_SOURCE', name='trustlevel'), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wellness_goals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('goal_type', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wellness_goals_user_id'), 'wellness_goals', ['user_id'], unique=False)
    op.create_table('external_sync_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('records_imported', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('sync_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['health_provider_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('domain_topic', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('freshness', sa.Enum('CURRENT', 'AGING', 'OUTDATED', 'SUPERSEDED', name='freshnessstatus'), nullable=False),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wellness_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', name='planfrequency'), nullable=False),
    sa.Column('status', sa.Enum('SUGGESTED', 'ACCEPTED', 'COMPLETED', 'SKIPPED', 'DISMISSED', name='planstatus'), nullable=False),
    sa.Column('reasoning', sa.String(), nullable=False),
    sa.Column('source_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['wellness_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wellness_plans_user_id'), 'wellness_plans', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # (Removed auto-generated drops of legacy tables)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (Removed auto-generated creates of legacy tables)
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_wellness_plans_user_id'), table_name='wellness_plans')
    op.drop_table('wellness_plans')
    op.drop_table('knowledge_documents')
    op.drop_table('external_sync_logs')
    op.drop_index(op.f('ix_wellness_goals_user_id'), table_name='wellness_goals')
    op.drop_table('wellness_goals')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_health_provider_connections_user_id'), table_name='health_provider_connections')
    op.drop_table('health_provider_connections')
    op.drop_index(op.f('ix_ai_observability_logs_user_id'), table_name='ai_observability_logs')
    op.drop_index(op.f('ix_ai_observability_logs_request_id'), table_name='ai_observability_logs')
    op.drop_table('ai_observability_logs')
    # ### end Alembic commands ###
